import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';

const emptyForm = { title: '', description: '', priority: 'medium', dueDate: '', tag: '', accent: 'violet', emoji: '' };
const priorityRank = { high: 0, medium: 1, low: 2 };
const accentOptions = ['violet', 'cyan', 'rose', 'amber', 'blue'];
const emojiOptions = ['', '\u2726', '\u2615', '\u270e', '\u2301', '\u2661', '\u26a1'];

function formatDate(value) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)); }
function isOverdue(task) { return task.dueDate && task.status !== 'complete' && new Date(`${task.dueDate}T23:59:59`) < new Date(); }
async function request(path, options = {}) { const response = await fetch(path, { headers: { 'content-type': 'application/json' }, ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error || 'The dashboard could not complete that request.'); return data; }

function TaskForm({ form, setForm, onSubmit, editingId, onCancel, busy }) {
  return <form className="task-form" onSubmit={onSubmit}>
    <div className="field"><label htmlFor="task-title">A little intention</label><input id="task-title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="What would you like to move forward?" required maxLength={100} /></div>
    <div className="field"><label htmlFor="task-description">Notes <span>Optional</span></label><textarea id="task-description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="A thought, a detail, a useful next step..." rows="3" maxLength={280} /></div>
    <div className="field-row"><div className="field"><label htmlFor="task-priority">Energy</label><select id="task-priority" value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><option value="high">High priority</option><option value="medium">Medium priority</option><option value="low">Low priority</option></select></div><div className="field"><label htmlFor="task-due-date">Due date <span>Optional</span></label><input id="task-due-date" type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></div></div>
    <div className="field"><label htmlFor="task-tag">Collection <span>Optional tag</span></label><input id="task-tag" value={form.tag} onChange={(event) => setForm({ ...form, tag: event.target.value })} placeholder="Studio, life, learning..." maxLength={24} /></div>
    <fieldset className="personalize-field"><legend>Make it yours</legend><div className="personalize-row"><div className="swatches" aria-label="Task accent color">{accentOptions.map((accent) => <button key={accent} type="button" className={`swatch ${accent} ${form.accent === accent ? 'selected' : ''}`} aria-label={`${accent} accent`} aria-pressed={form.accent === accent} onClick={() => setForm({ ...form, accent })} />)}</div><label className="emoji-select" htmlFor="task-emoji"><span>Mark</span><select id="task-emoji" value={form.emoji} onChange={(event) => setForm({ ...form, emoji: event.target.value })}>{emojiOptions.map((emoji) => <option key={emoji || 'none'} value={emoji}>{emoji || 'None'}</option>)}</select></label></div></fieldset>
    <div className="form-actions">{editingId && <button className="button button-quiet" type="button" onClick={onCancel}>Cancel</button>}<button className="button button-primary" type="submit" disabled={busy}>{busy ? 'Saving...' : editingId ? 'Save intention' : 'Add to the day'} <span aria-hidden="true">+</span></button></div>
  </form>;
}

function TaskCard({ task, expanded, draggable, dragging, removing, onToggle, onEdit, onDelete, onPin, onExpand, onDragStart, onDragOver, onDrop, onDragEnd }) {
  return <article className={`task-card accent-${task.accent || 'violet'} priority-${task.priority} ${task.status === 'complete' ? 'is-complete' : ''} ${expanded ? 'expanded' : ''} ${dragging ? 'dragging' : ''} ${removing ? 'removing' : ''}`} draggable={draggable} onDragStart={(event) => onDragStart(event, task)} onDragOver={onDragOver} onDrop={(event) => onDrop(event, task)} onDragEnd={onDragEnd}>
    <span className="drag-grip" aria-hidden="true" title="Drag to reorder">DRAG</span>
    <button className="task-check" type="button" onClick={() => onToggle(task)} aria-label={`${task.status === 'complete' ? 'Mark' : 'Complete'} ${task.title}`} aria-pressed={task.status === 'complete'}><span aria-hidden="true" /></button>
    <button className="task-main" type="button" onClick={() => onExpand(task.id)} aria-expanded={expanded} aria-label={`${expanded ? 'Collapse' : 'Expand'} details for ${task.title}`}><span className="task-heading"><span className="task-emoji" aria-hidden="true">{task.emoji || ' '}</span><strong>{task.title}</strong><span className={`status-pill ${task.status}`}>{task.status}</span></span><span className="task-summary">{task.description || 'A small step, kept in view.'}</span><span className="task-details">{task.tag && <span className="tag-chip">{task.tag}</span>}{task.dueDate && <time className={isOverdue(task) ? 'overdue' : ''} dateTime={task.dueDate}>{isOverdue(task) ? 'Overdue' : 'Due'} {formatDate(task.dueDate)}</time>}<time dateTime={task.createdAt}>Added {formatDate(task.createdAt)}</time></span></button>
    <div className="task-actions"><button type="button" className={`pin-action ${task.pinned ? 'pinned' : ''}`} onClick={() => onPin(task)} aria-label={`${task.pinned ? 'Unpin' : 'Pin'} ${task.title}`} aria-pressed={Boolean(task.pinned)} title={task.pinned ? 'Unpin task' : 'Pin task'}>P</button><button type="button" onClick={() => onEdit(task)} aria-label={`Edit ${task.title}`}>Edit</button><button type="button" className="delete-action" onClick={() => onDelete(task)} aria-label={`Delete ${task.title}`}>x</button></div>
    {expanded && <div className="task-expanded"><div><span>Priority</span><strong>{task.priority}</strong></div><div><span>Created</span><strong>{formatDate(task.createdAt)}</strong></div>{task.dueDate && <div><span>Due</span><strong className={isOverdue(task) ? 'overdue' : ''}>{formatDate(task.dueDate)}</strong></div>}<p>{task.description || 'No extra notes for this intention.'}</p><span className="drag-hint">Drag card to arrange your day</span></div>}
  </article>;
}

export default function App() {
  const [tasks, setTasks] = useState([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [sort, setSort] = useState('manual'); const [toast, setToast] = useState(null); const [expandedId, setExpandedId] = useState(null); const [dragId, setDragId] = useState(null); const [removingIds, setRemovingIds] = useState([]); const [theme, setTheme] = useState(() => localStorage.getItem('daymark-theme') || 'dark'); const [celebrate, setCelebrate] = useState(false); const wasAllComplete = useRef(false); const hasCompletedAction = useRef(false); const editScrollPosition = useRef(0); const deleteTimers = useRef(new Map());
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('daymark-theme', theme); }, [theme]);
  async function loadTasks() { setLoading(true); setError(''); try { const data = await request('/api/tasks'); setTasks(data.tasks); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { loadTasks(); }, []);
  async function handleSubmit(event) { event.preventDefault(); setBusy(true); setError(''); try { const data = editingId ? await request(`/api/tasks/${editingId}`, { method: 'PATCH', body: JSON.stringify(form) }) : await request('/api/tasks', { method: 'POST', body: JSON.stringify(form) }); setTasks((current) => editingId ? current.map((task) => task.id === editingId ? data.task : task) : [data.task, ...current]); setForm(emptyForm); setEditingId(null); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function handleToggle(task) { hasCompletedAction.current = true; setError(''); try { const data = await request(`/api/tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status: task.status === 'complete' ? 'pending' : 'complete' }) }); setTasks((current) => current.map((item) => item.id === task.id ? data.task : item)); } catch (err) { setError(err.message); } }
  function startEdit(task) { editScrollPosition.current = window.scrollY; setEditingId(task.id); setForm({ title: task.title, description: task.description, priority: task.priority, dueDate: task.dueDate, tag: task.tag, accent: task.accent || 'violet', emoji: task.emoji || '' }); }
  useLayoutEffect(() => { if (editingId) window.scrollTo(0, editScrollPosition.current); }, [editingId]);
  async function handlePin(task) { try { const data = await request(`/api/tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ pinned: !task.pinned }) }); setTasks((current) => current.map((item) => item.id === task.id ? data.task : item)); } catch (err) { setError(err.message); } }
  function handleDelete(task) { setRemovingIds((current) => [...current, task.id]); setToast({ task }); const timer = window.setTimeout(() => commitDelete(task), 5000); deleteTimers.current.set(task.id, timer); window.setTimeout(() => { if (deleteTimers.current.has(task.id)) setTasks((current) => current.filter((item) => item.id !== task.id)); setRemovingIds((current) => current.filter((id) => id !== task.id)); }, 280); }
  async function commitDelete(task) { deleteTimers.current.delete(task.id); try { await request(`/api/tasks/${task.id}`, { method: 'DELETE' }); } catch (err) { setError(err.message); setTasks((current) => [task, ...current]); } setToast((current) => current?.task.id === task.id ? null : current); }
  function undoDelete() { if (!toast) return; const { task } = toast; const timer = deleteTimers.current.get(task.id); if (timer) window.clearTimeout(timer); deleteTimers.current.delete(task.id); setTasks((current) => current.some((item) => item.id === task.id) ? current : [task, ...current]); setRemovingIds((current) => current.filter((id) => id !== task.id)); setToast(null); }
  const completed = useMemo(() => tasks.filter((task) => task.status === 'complete').length, [tasks]);
  useEffect(() => { const allDone = tasks.length > 0 && completed === tasks.length; if (hasCompletedAction.current && allDone && !wasAllComplete.current) { setCelebrate(true); window.setTimeout(() => setCelebrate(false), 2400); } wasAllComplete.current = allDone; }, [tasks.length, completed]);
  const filteredTasks = useMemo(() => { const result = tasks.filter((task) => { const matchesQuery = `${task.title} ${task.description} ${task.tag}`.toLowerCase().includes(query.toLowerCase()); const matchesFilter = filter === 'all' || (filter === 'active' ? task.status === 'pending' : task.status === 'complete'); return matchesQuery && matchesFilter; }); return [...result].sort((a, b) => Number(Boolean(b.pinned)) - Number(Boolean(a.pinned)) || (sort === 'priority' ? priorityRank[a.priority] - priorityRank[b.priority] : sort === 'due' ? (a.dueDate || '9999').localeCompare(b.dueDate || '9999') : sort === 'created' ? new Date(b.createdAt) - new Date(a.createdAt) : (a.sortOrder || a.id) - (b.sortOrder || b.id))); }, [tasks, query, filter, sort]);
  function dragStart(event, task) { if (sort !== 'manual' || filter !== 'all' || query) { event.preventDefault(); return; } setDragId(task.id); event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', String(task.id)); }
  function dragOver(event) { if (dragId !== null) { event.preventDefault(); event.dataTransfer.dropEffect = 'move'; } }
  async function dropTask(event, target) { event.preventDefault(); const sourceId = Number(event.dataTransfer.getData('text/plain')) || dragId; if (!sourceId || sourceId === target.id) return; const reordered = [...filteredTasks]; const from = reordered.findIndex((task) => task.id === sourceId); const to = reordered.findIndex((task) => task.id === target.id); if (from < 0 || to < 0) return; const [moved] = reordered.splice(from, 1); reordered.splice(to, 0, moved); const ids = reordered.map((task) => task.id); setTasks((current) => { const order = new Map(ids.map((id, index) => [id, index + 1])); return current.map((task) => ({ ...task, sortOrder: order.get(task.id) ?? task.sortOrder })); }); setSort('manual'); try { const data = await request('/api/tasks/order', { method: 'PUT', body: JSON.stringify({ ids }) }); setTasks(data.tasks); } catch (err) { setError(err.message); loadTasks(); } }
  const allComplete = tasks.length > 0 && completed === tasks.length;
  return <div className={`app-shell ${theme}`}><header className="topbar"><a className="brand" href="#top" aria-label="Daymark home"><span className="brand-mark">d.</span><span>daymark</span></a><div className="topbar-right"><span className="topbar-meta"><span className="pulse-dot" aria-hidden="true"></span> Your private space</span><button className="theme-toggle" type="button" aria-label={`Switch to ${theme === 'dark' ? 'light' : 'dark'} theme`} onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}><span className={`theme-symbol ${theme}`} aria-hidden="true" /></button></div></header><main id="top" className="dashboard-shell">
    <section className="dashboard-intro"><div><p className="eyebrow"><span>YOUR DAY, IN GOOD ORDER</span><span className="eyebrow-line" /></p><h1>Make space for<br /><em>what matters.</em></h1><p className="intro-copy">A softer place to gather your thoughts, set an intention, and move at your own pace.</p></div><div className="progress-card"><div className="progress-label"><span>Today's rhythm</span><span>{tasks.length ? Math.round(completed / tasks.length * 100) : 0}%</span></div><strong>{completed}<small> of {tasks.length} complete</small></strong><div className="progress-track"><span style={{ width: tasks.length ? `${completed / tasks.length * 100}%` : '0%' }} /></div><p>{allComplete ? 'A clear page. Well done.' : `${tasks.length - completed} intentions still in motion`}</p></div></section>
    {error && <div className="error-banner" role="alert"><strong>A small interruption.</strong><span>{error}</span><button type="button" onClick={loadTasks}>Retry</button></div>}
    <section className="workspace-grid" aria-label="Task workspace"><aside className="composer-panel"><div className="panel-heading"><div><span className="section-number">01 / INTENTION</span><h2>{editingId ? 'Shape the thought' : 'Begin somewhere.'}</h2></div><span className="panel-icon" aria-hidden="true">+</span></div><TaskForm form={form} setForm={setForm} onSubmit={handleSubmit} editingId={editingId} onCancel={() => { setEditingId(null); setForm(emptyForm); }} busy={busy} /><p className="composer-note">Small rituals make room for meaningful work.</p></aside>
      <section className="tasks-panel"><div className="panel-heading"><div><span className="section-number">02 / YOUR LIST</span><h2>The day, unfolding.</h2></div><span className="task-count">{filteredTasks.length.toString().padStart(2, '0')}</span></div><div className="task-toolbar"><label className="search-field"><span className="search-symbol" aria-hidden="true" /><input aria-label="Search tasks" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a thought..." /></label><div className="filter-tabs" role="tablist" aria-label="Task filters">{[['all', 'All'], ['active', 'Open'], ['completed', 'Done']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} type="button" role="tab" aria-selected={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div><label className="sort-field"><span>Order</span><select aria-label="Sort tasks" value={sort} onChange={(event) => setSort(event.target.value)}><option value="manual">My order</option><option value="created">Recently added</option><option value="due">Due date</option><option value="priority">Priority</option></select></label></div>
        {celebrate && <div className="celebration" role="status"><span className="celebration-star" aria-hidden="true" /><strong>Everything is in its place.</strong><span className="celebration-star" aria-hidden="true" /></div>}
        {loading ? <div className="state-card"><span className="loader" aria-hidden="true"></span><p>Gathering your thoughts...</p></div> : filteredTasks.length === 0 ? <div className="state-card empty-state"><span className="empty-mark" aria-hidden="true" /><h3>{tasks.length ? 'Nothing found.' : 'A fresh page.'}</h3><p>{tasks.length ? 'Try another phrase or view.' : 'Add a thought when you are ready.'}</p></div> : <div className="task-list">{filteredTasks.map((task) => <TaskCard key={task.id} task={task} expanded={expandedId === task.id} removing={removingIds.includes(task.id)} dragging={dragId === task.id} draggable={sort === 'manual' && filter === 'all' && !query} onToggle={handleToggle} onEdit={startEdit} onDelete={handleDelete} onPin={handlePin} onExpand={(id) => setExpandedId(expandedId === id ? null : id)} onDragStart={dragStart} onDragOver={dragOver} onDrop={dropTask} onDragEnd={() => setDragId(null)} />)}</div>}
      </section></section>
  </main><footer className="app-footer"><span>Daymark <i>|</i> a little more intentional</span><span>Made for your everyday</span></footer>{toast && <div className="toast" role="status"><span>Intention tucked away.</span><button type="button" onClick={undoDelete}>Undo</button></div>}</div>;
}
