import { useEffect, useLayoutEffect, useMemo, useRef, useState } from 'react';

const emptyForm = { title: '', description: '', priority: 'medium', dueDate: '', tag: '' };
const priorityRank = { high: 0, medium: 1, low: 2 };

function formatDate(value) { return new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(value)); }
function isOverdue(task) { return task.dueDate && task.status !== 'complete' && new Date(`${task.dueDate}T23:59:59`) < new Date(); }
async function request(path, options = {}) { const response = await fetch(path, { headers: { 'content-type': 'application/json' }, ...options }); const data = response.status === 204 ? null : await response.json(); if (!response.ok) throw new Error(data?.error || 'The dashboard could not complete that request.'); return data; }

function TaskForm({ form, setForm, onSubmit, editingId, onCancel, busy }) {
  return <form className="task-form" onSubmit={onSubmit}>
    <div className="field field-title"><label htmlFor="task-title">Task title</label><input id="task-title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="e.g. Prepare project handoff" required maxLength={100} /></div>
    <div className="field"><label htmlFor="task-description">Description <span>Optional</span></label><textarea id="task-description" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} placeholder="Add context or the next step..." rows="3" maxLength={280} /></div>
    <div className="field-row"><div className="field"><label htmlFor="task-priority">Priority</label><select id="task-priority" value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value })}><option value="high">High priority</option><option value="medium">Medium priority</option><option value="low">Low priority</option></select></div><div className="field"><label htmlFor="task-due-date">Due date <span>Optional</span></label><input id="task-due-date" type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></div></div>
    <div className="field"><label htmlFor="task-tag">Tag <span>Optional</span></label><input id="task-tag" value={form.tag} onChange={(event) => setForm({ ...form, tag: event.target.value })} placeholder="Work, personal, study..." maxLength={24} /></div>
    <div className="form-actions">{editingId && <button className="button button-quiet" type="button" onClick={onCancel}>Cancel</button>}<button className="button button-primary" type="submit" disabled={busy}>{busy ? 'Saving...' : editingId ? 'Save changes' : 'Add task'} <span aria-hidden="true">{editingId ? '↗' : '+'}</span></button></div>
  </form>;
}

function TaskCard({ task, onToggle, onEdit, onDelete }) {
  return <article className={`task-card priority-${task.priority} ${task.status === 'complete' ? 'is-complete' : ''}`}>
    <button className="task-check" type="button" onClick={() => onToggle(task)} aria-label={`${task.status === 'complete' ? 'Mark' : 'Complete'} ${task.title}`} aria-pressed={task.status === 'complete'}><span aria-hidden="true">{task.status === 'complete' ? '✓' : ''}</span></button>
    <div className="task-content"><div className="task-heading"><h3>{task.title}</h3><span className={`status-pill ${task.status}`}>{task.status}</span></div>{task.description && <p>{task.description}</p>}<div className="task-details">{task.tag && <span className="tag-chip">{task.tag}</span>}{task.dueDate && <time className={isOverdue(task) ? 'overdue' : ''} dateTime={task.dueDate}>{isOverdue(task) ? 'Overdue' : 'Due'} {formatDate(task.dueDate)}</time>}<time dateTime={task.createdAt}>Added {formatDate(task.createdAt)}</time></div></div>
    <div className="task-actions"><button type="button" onClick={() => onEdit(task)} aria-label={`Edit ${task.title}`}>Edit</button><button type="button" className="delete-action" onClick={() => onDelete(task)} aria-label={`Delete ${task.title}`}>Delete</button></div>
  </article>;
}

export default function App() {
  const [tasks, setTasks] = useState([]); const [form, setForm] = useState(emptyForm); const [editingId, setEditingId] = useState(null); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [sort, setSort] = useState('created'); const [toast, setToast] = useState(null); const editScrollPosition = useRef(0);
  async function loadTasks() { setLoading(true); setError(''); try { const data = await request('/api/tasks'); setTasks(data.tasks); } catch (err) { setError(err.message); } finally { setLoading(false); } }
  useEffect(() => { loadTasks(); }, []);
  async function handleSubmit(event) { event.preventDefault(); setBusy(true); setError(''); try { const data = editingId ? await request(`/api/tasks/${editingId}`, { method: 'PATCH', body: JSON.stringify(form) }) : await request('/api/tasks', { method: 'POST', body: JSON.stringify(form) }); setTasks((current) => editingId ? current.map((task) => task.id === editingId ? data.task : task) : [data.task, ...current]); setForm(emptyForm); setEditingId(null); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  async function handleToggle(task) { setError(''); try { const data = await request(`/api/tasks/${task.id}`, { method: 'PATCH', body: JSON.stringify({ status: task.status === 'complete' ? 'pending' : 'complete' }) }); setTasks((current) => current.map((item) => item.id === task.id ? data.task : item)); } catch (err) { setError(err.message); } }
  function startEdit(task) { editScrollPosition.current = window.scrollY; setEditingId(task.id); setForm({ title: task.title, description: task.description, priority: task.priority, dueDate: task.dueDate, tag: task.tag }); }
  useLayoutEffect(() => { if (editingId) window.scrollTo(0, editScrollPosition.current); }, [editingId]);
  function handleDelete(task) { setTasks((current) => current.filter((item) => item.id !== task.id)); setToast({ task }); }
  async function commitDelete(task) { try { await request(`/api/tasks/${task.id}`, { method: 'DELETE' }); } catch (err) { setError(err.message); setTasks((current) => [task, ...current]); } }
  function undoDelete() { if (!toast) return; setTasks((current) => [toast.task, ...current]); setToast(null); }
  useEffect(() => { if (!toast) return undefined; const timer = window.setTimeout(() => { commitDelete(toast.task); setToast(null); }, 5000); return () => window.clearTimeout(timer); }, [toast]);
  const completed = useMemo(() => tasks.filter((task) => task.status === 'complete').length, [tasks]); const filteredTasks = useMemo(() => { const result = tasks.filter((task) => { const matchesQuery = `${task.title} ${task.description} ${task.tag}`.toLowerCase().includes(query.toLowerCase()); const matchesFilter = filter === 'all' || (filter === 'active' ? task.status === 'pending' : task.status === 'complete'); return matchesQuery && matchesFilter; }); return [...result].sort((a, b) => sort === 'priority' ? priorityRank[a.priority] - priorityRank[b.priority] : sort === 'due' ? (a.dueDate || '9999').localeCompare(b.dueDate || '9999') : new Date(b.createdAt) - new Date(a.createdAt)); }, [tasks, query, filter, sort]);
  return <div className="app-shell"><header className="topbar"><a className="brand" href="#top" aria-label="Daymark home"><span className="brand-mark">D</span><span>daymark</span></a><div className="topbar-meta"><span className="pulse-dot" aria-hidden="true"></span> Local workspace</div></header><main id="top" className="dashboard-shell">
    <section className="dashboard-intro"><div><p className="eyebrow">Personal task dashboard</p><h1>Make room for<br /><em>what matters.</em></h1><p className="intro-copy">A calm place to collect the work in front of you, one clear next step at a time.</p></div><div className="progress-card"><div><span>Progress</span><strong>{completed} <small>of {tasks.length} complete</small></strong></div><div className="progress-track"><span style={{ width: tasks.length ? `${completed / tasks.length * 100}%` : '0%' }} /></div></div></section>
    {error && <div className="error-banner" role="alert"><strong>Something needs attention.</strong><span>{error}</span><button type="button" onClick={loadTasks}>Try again</button></div>}
    <section className="workspace-grid" aria-label="Task workspace"><div className="composer-panel"><div className="panel-heading"><div><span className="section-number">01</span><h2>{editingId ? 'Refine this task' : 'Add a task'}</h2></div><span className="panel-icon" aria-hidden="true">✦</span></div><TaskForm form={form} setForm={setForm} onSubmit={handleSubmit} editingId={editingId} onCancel={() => { setEditingId(null); setForm(emptyForm); }} busy={busy} /><p className="composer-note">Keep it specific. Small, clear tasks are easier to move forward.</p></div>
      <div className="tasks-panel"><div className="panel-heading"><div><span className="section-number">02</span><h2>Your tasks</h2></div><span className="task-count">{filteredTasks.length.toString().padStart(2, '0')}</span></div><div className="task-toolbar"><label className="search-field"><span aria-hidden="true">⌕</span><input aria-label="Search tasks" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search tasks..." /></label><div className="filter-tabs" role="tablist" aria-label="Task filters">{[['all', 'All'], ['active', 'Active'], ['completed', 'Completed']].map(([value, label]) => <button key={value} className={filter === value ? 'active' : ''} type="button" role="tab" aria-selected={filter === value} onClick={() => setFilter(value)}>{label}</button>)}</div><label className="sort-field">Sort by <select aria-label="Sort tasks" value={sort} onChange={(event) => setSort(event.target.value)}><option value="created">Date created</option><option value="due">Due date</option><option value="priority">Priority</option></select></label></div>{loading ? <div className="state-card"><span className="loader" aria-hidden="true"></span><p>Loading your workspace...</p></div> : filteredTasks.length === 0 ? <div className="state-card empty-state"><span className="empty-mark" aria-hidden="true">○</span><h3>{tasks.length ? 'No matching tasks.' : 'Nothing here yet.'}</h3><p>{tasks.length ? 'Try a different search or filter.' : 'Add your first task and give the day a direction.'}</p></div> : <div className="task-list">{filteredTasks.map((task) => <TaskCard key={task.id} task={task} onToggle={handleToggle} onEdit={startEdit} onDelete={handleDelete} />)}</div>}</div></section>
  </main><footer className="app-footer"><span>Daymark / Task 03</span><span>Built for focused progress</span></footer>{toast && <div className="toast" role="status"><span>Task deleted.</span><button type="button" onClick={undoDelete}>Undo</button></div>}</div>;
}
